import React from "react";
import PropTypes from "prop-types";
import styles from "./styles.scss";

const Policy = (props, context) => (
  <main className={styles.policy}>
    <div className={styles.policyMain__logo}>
      <a href="/">
        <img src={require("images/logo.png")} alt={context.t("Logo")}/>
      </a>
    </div>
    <div className={styles.policyInfo}>
      <p className={styles.paragraphTitle}>Privacy Policy</p>
      <p className={styles.policyContent}>This Privacy Policy describes the policies and procedures of Lisztfever (“we”, “our” or “us”) on the collection, use and disclosure of your information on the Lisztfever apps (the “Apps”), the Lisztfever we offer through third party messaging services (the “Bots”) and our website at ticketbotai.com (collectively, the “Services”). We receive information about you from various sources, including: (i) your use of the Services generally; and (ii) from third party websites and services. When you use the Services, you are consenting to the collection, transfer, manipulation, storage, disclosure and other uses of your information as described in this Privacy Policy.</p>
      <p className={styles.policySubtitle__q}>WHAT DOES THIS PRIVACY POLICY COVER?</p>
      <p className={styles.policySubtitle__p}></p>
      <p className={styles.policyContent}>This Privacy Policy covers the treatment of personally identifiable information (“Personal Information”) gathered when you are using or accessing the Services.  Furthermore, this Privacy Policy covers our treatment of any Personal Information that our business partners share with us or that we share with our business partners.<br/>
      This Privacy Policy does not apply to the practices of third parties that we do not own or control, including but not limited to any third party messaging services, mobile device and wireless providers, websites, services and applications (collectively, the “Third Party Services”) that you elect to access through the Service or to individuals that we do not manage or employ. While we attempt to facilitate access only to those Third Party Services that share our respect for your privacy, we cannot take responsibility for the content or privacy policies of those Third Party Services. We encourage you to carefully review the privacy policies of any Third Party Services you access.</p>
      <p className={styles.policySubtitle__q}>WHAT INFORMATION DO WE COLLECT?</p>
      <p className={styles.policyContent}>The information we gather enables us to personalize, improve and continue to operate the Services. In connection with certain aspects of the Services, we may request, collect and/or display some of your Personal Information. We collect the following types of information from our users.</p>
      <p className={styles.policySubtitle__p}>ACCOUNT INFORMATION:</p>
      <p className={styles.policyContent}>When you create an account on the Services (“Account”), you will provide information that could be Personal Information, such as your name, email address and phone number. You acknowledge that this information may be personal to you, and by creating an Account on the Services and providing Personal Information to us, you allow others, including us, to identify you and therefore may not be anonymous. We may use your email address to send you notifications if you opt in to such notifications through your Account settings. We may also use your contact information to send you information about our Services.</p>
      <p className={styles.policySubtitle__p}>USER CONTENT:</p>
      <p className={styles.policyContent}>Some features of the Services allow you to provide content to the Services. All content submitted by you to the Services may be retained by us indefinitely, even if and after your access to the Services is terminated. We may continue to disclose such content to third parties in a manner that does not reveal Personal Information, as described in this Privacy Policy.</p>
      <p className={styles.policySubtitle__p}>LOCATION INFORMATION:</p>
      <p className={styles.policyContent}>The Apps and Services include features based on users’ actual locations and tracking users’ current locations (“Location-Based Services”). To the extent you voluntarily use any Location-Based Services, we will collect and store information about your location at the time you use those Location-Based Services, and will use such information in order to provide you the Location-Based Services and to improve the Services. We obtain this information through your device. You can always choose to opt out of the Location-Based Services by changing the settings on your device to stop our collection of your location information.</p>
      <p className={styles.policySubtitle__p}>INFORMATION COLLECTED THROUGH THE BOTS:</p>
      <p className={styles.policyContent}>We offer the Bots through third party messaging services, including Facebook Messenger. When you access or interact with the Bots on such Third Party Services, we receive certain information from such Third Party Services in connection with your use of the Bots and your account on such Third Party Services. We use such information in accordance with such Third Party Services’ respective policies and your account privacy settings selected through your account on such Third Party Services. You agree to the policies of the applicable Third Party Services in your use of the Bots, and acknowledge and agree that you are solely responsible for your use of such Third Party Services.<br/>
      Please note that the communications you have with the Bots are not private and that we may share or publish publicly any part of your conversations or interactions with the Bots. We therefore urge you to think carefully about including any Personal Information or other specific information you may deem private in your communications with the Bots.</p>
      <p className={styles.policySubtitle__p}>INFORMATION COLLECTED USING COOKIES:</p>
      <p className={styles.policyContent}>Cookies are pieces of text that may be provided to your computer through your browser when you access a website. Your browser stores cookies in a manner associated with each website you visit. We use cookies to enable our servers to recognize your browser and tell us how and when you use the Services through the Internet. Our cookies do not, by themselves, contain Personal Information, and we do not combine the general information collected through cookies with other Personal Information to tell us who you are. As noted, however, we do use cookies to identify that your browser has accessed aspects of the Services. Most browsers have an option for turning off the cookie feature, which will prevent your browser from accepting new cookies, as well as (depending on the sophistication of your browser software) allowing you to decide on acceptance of each new cookie in a variety of ways. We strongly recommend that you leave cookies active, because they enable you to take advantage of some features of the Services.
      <br/>
      This Privacy Policy covers our use of cookies only and does not cover the use of cookies by third parties. We do not control when or how third parties place cookies on your computer or device. For example, third party websites to which a link points may set cookies on your computer.</p>
      <p className={styles.policySubtitle__p}>INFORMATION RELATED TO ADVERTISING:</p>
      <p className={styles.policyContent}>To support and enhance the Services, we may serve advertisements, and also allow third parties to serve advertisements, through the Services. These advertisements are sometimes targeted and served to particular users and may come from third party companies called “ad networks.” Ad networks include third party ad servers, ad agencies, ad technology vendors and research firms.<br/>
      Advertisements served through the Services may be targeted to users who fit a certain general profile category, may be based on anonymized information inferred from information provided to us by a user (including Personal Information, e.g., gender or age), may be based on the Services usage patterns of particular users, may be based on users’ location information collected through the Location-Based Services, or may be based on users’ activity on Third Party Services. We do not provide Personal Information to any ad networks for use outside of the Services.</p>
      <p className={styles.policySubtitle__p}>AGGREGATE INFORMATION:</p>
      <p className={styles.policyContent}>We collect statistical information about how users, collectively, use the Services (“Aggregate Information”). Some of this information is derived from Personal Information. This statistical information is not Personal Information and cannot be tied back to you, or your browser or device.</p>
      <p className={styles.policySubtitle__q}>HOW, AND WITH WHOM, IS MY INFORMATION SHARED?</p>
      <p className={styles.policyContent}>The Services are designed to help you share information with others. As a result, some of the information generated through the Services is shared publicly or with third parties.</p>
      <p className={styles.policySubtitle__p}>PUBLIC INFORMATION ABOUT YOUR ACTIVITY ON THE SERVICES:</p>
      <p className={styles.policyContent}>Some of your activity on and through the Services is public by default. This may include, but is not limited to, content you have posted publicly through the Services.<br/>
      Information concerning your use of the Services may be tracked anonymously through the use of cookies and stored by us.<br/>
      Please also remember that if you choose to provide Personal Information using certain public features of the Services, then that information is governed by the privacy settings of those particular features and may be publicly available. Individuals reading such information may use or disclose it to other individuals or entities without our control and without your knowledge, and search engines may index that information. We therefore urge you to think carefully about including any specific information you may deem private in content that you create or information that you submit through the Services.</p>
      <p className={styles.policySubtitle__p}>INFORMATION COLLECTED THROUGH THE BOTS:</p>
      <p className={styles.policyContent}>We may share your information with the Third Party Services on which we offer the Bots, in order to provide you the Bots. Please note that the communications you have with the Bots on Third Party Services are not private and that we may share or publish publicly any part of your conversations or interactions with the Bots. We therefore urge you to think carefully about including any Personal Information or other specific information you may deem private in your communications with the Bots. In addition, please carefully review the policies of the applicable Third Party Services, including their data usage and sharing practices.</p>
      <p className={styles.policySubtitle__p}>INFORMATION YOU ELECT TO SHARE:</p>
      <p className={styles.policyContent}>You may access other Third Party Services through the Services, for example by clicking on links to those Third Party Services from within the Services or by interacting with the Bots on Third Party Services. We are not responsible for the privacy policies and/or practices of these Third Party Services, and you are responsible for reading and understanding those Third Party Services’ privacy policies. This Privacy Policy only governs information collected on the Services.</p>
      <p className={styles.policySubtitle__p}>AGGREGATE INFORMATION:</p>
      <p className={styles.policyContent}>We share Aggregate Information with our partners, service providers and other persons with whom we conduct business. We share this type of statistical data so that our partners can understand how and how often people use our Services and their services or websites, which facilitates improving both their services and how our Services interface with them. In addition, these third parties may share with us non-private, aggregated or otherwise non Personal Information about you that they have independently developed or acquired.</p>
      <p className={styles.policySubtitle__p}>INFORMATION SHARED WITH OUR AGENTS:</p>
      <p className={styles.policyContent}>We employ and contract with people and other entities that perform certain tasks on our behalf and who are under our control (our “Agents”). We may need to share Personal Information with our Agents in order to provide products or services to you. Unless we tell you differently, our Agents do not have any right to use Personal Information or other information we share with them beyond what is necessary to assist us. You hereby consent to our sharing of Personal Information with our Agents.</p>
      <p className={styles.policySubtitle__p}>INFORMATION DISCLOSED PURSUANT TO BUSINESS TRANSFERS:</p>
      <p className={styles.policyContent}>In some cases, we may choose to buy or sell assets. In these types of transactions, user information is typically one of the transferred business assets. Moreover, if we, or substantially all of our assets, were acquired, or if we go out of business or enter bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of us or our assets may continue to use your Personal Information as set forth in this policy.</p>
      <p className={styles.policySubtitle__p}>INFORMATION DISCLOSED FOR OUR PROTECTION AND THE PROTECTION OF OTHERS:</p>
      <p className={styles.policyContent}>We also reserve the right to access, read, preserve, and disclose any information as it reasonably believes is necessary to (i) satisfy any applicable law, regulation, legal process or governmental request, (ii) enforce these Terms of Service, including investigation of potential violations hereof, (iii) detect, prevent, or otherwise address fraud, security or technical issues, (iv) respond to user support requests, or (v) protect our rights, property or safety, our users and the public. This includes exchanging information with other companies and organizations for fraud protection and spam/malware prevention.</p>
      <p className={styles.policySubtitle__p}>INFORMATION WE SHARE WITH YOUR CONSENT:</p>
      <p className={styles.policyContent}>Except as set forth above, you will be notified when your Personal Information may be shared with third parties, and will be able to prevent the sharing of this information.</p>
      <p className={styles.policySubtitle__q}>IS INFORMATION ABOUT ME SECURE?</p>
      <p className={styles.policyContent}>We seek to protect user information to ensure that it is kept private; however, we cannot guarantee the security of any user information. Unauthorized entry or use, hardware or software failure, and other factors, may compromise the security of user information at any time.<br/>
        We otherwise store all of our information using industry-standard techniques. We do not guarantee or warrant that such techniques will prevent unauthorized access to information about you that we store, Personal Information or otherwise.</p>
      <p className={styles.policySubtitle__q}>WHAT INFORMATION OF MINE CAN I ACCESS?</p>
      <p className={styles.policyContent}>You can access information associated with your Account by logging into the Services. Users can access and delete cookies through their browser and device settings.<br/>
      California Privacy Rights: Under California Civil Code sections 1798.83-1798.84, California residents are entitled to ask us for a notice identifying the categories of personal customer information which we share with our affiliates and/or third parties for marketing purposes, and providing contact information for such affiliates and/or third parties. If you are a California resident and would like a copy of this notice, please submit a written request to the following address: 21 Seonhwa-ro 214beon-gil, Dong-gu, Daejeon, South Korea</p>
      <p className={styles.policySubtitle__q}>WHAT CHOICES DO I HAVE REGARDING MY INFORMATION?</p>
      <p className={styles.policyContent}>You can use many of the features of the Services without registering, thereby limiting the type of information that we collect.<br/>
      You can always opt not to disclose certain information to us, even though it may be needed to take advantage of some of our features.</p>
      <p className={styles.policySubtitle__q}>WHAT HAPPENS WHEN THERE ARE CHANGES TO THIS PRIVACY POLICY?</p>
      <p className={styles.policyContent}>We may amend this Privacy Policy from time to time. Use of information we collect now is subject to the Privacy Policy in effect at the time such information is used. If we make changes in the way we collect or use information, we will notify you by posting an announcement on the Services. A user is bound by any changes to the Privacy Policy when he or she uses the Services after such changes have been first posted.</p>
      <p className={styles.policySubtitle__q}>WHAT IF I HAVE QUESTIONS OR CONCERNS?</p>
      <p className={styles.policyContent}>If you have any questions or concerns regarding privacy using the Services, please send us a detailed message to legal@areha.io. We will do our very best to resolve your concerns.<br/>
      Effective Date: February 1, 2018.</p>
    </div>
  </main>
)

Policy.contextTypes = {
  t: PropTypes.func.isRequired
};

export default Policy;
