# Generated by Django 2.0.4 on 2018-06-25 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='event',
            field=models.ForeignKey(db_column='eventId', on_delete=django.db.models.deletion.PROTECT, to='events.Events'),
        ),
    ]
