# Generated by Django 2.0.4 on 2018-05-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followartist',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='followartist',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_artists',
        ),
        migrations.AlterField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', null=True),
        ),
        migrations.DeleteModel(
            name='FollowArtist',
        ),
    ]
