# Generated by Django 2.0.4 on 2018-06-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180625_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='event',
            field=models.ForeignKey(db_column='eventId', on_delete=django.db.models.deletion.CASCADE, to='events.Events'),
        ),
    ]
