# Generated by Django 2.0.4 on 2018-05-08 11:25

from django.db import migrations, models
import lisztfeverapp.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180504_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(db_column='profilePic', max_length=1025, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=lisztfeverapp.users.models.UnixTimestampField(auto_created=True, db_column='updatedAt', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='updated_at',
            field=lisztfeverapp.users.models.UnixTimestampField(auto_created=True, db_column='updatedAt', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not-specified', 'Not specified')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
