# Generated by Django 2.0.4 on 2018-05-08 11:55

from django.db import migrations, models
import lisztfeverapp.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180508_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_session_at',
            field=lisztfeverapp.users.models.UnixTimestampField(db_column='lastSessionAt', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sessions',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
