# Generated by Django 2.0.4 on 2018-06-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180625_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_events',
        ),
        migrations.AlterField(
            model_name='plan',
            name='event',
            field=models.CharField(db_column='eventId', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='user',
            field=models.CharField(db_column='userId', max_length=255, null=True),
        ),
    ]
