# Generated by Django 2.0.4 on 2018-05-22 03:28

from django.db import migrations
import lisztfeverapp.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180522_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=lisztfeverapp.users.models.UnixTimestampField(auto_created=True, db_column='createdAt', null=True),
        ),
    ]
