# Generated by Django 2.0.4 on 2018-05-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180508_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sessions',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
