# Generated by Django 2.0.4 on 2018-05-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180508_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-event__eventstartlocaldate']},
        ),
    ]
