# Generated by Django 2.0.4 on 2018-05-11 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180511_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={},
        ),
        migrations.AlterField(
            model_name='plan',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='plan',
            order_with_respect_to='event',
        ),
    ]
