# Generated by Django 2.0.4 on 2018-05-01 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_venue'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='artists',
            options={'ordering': ['-popularity']},
        ),
        migrations.AddField(
            model_name='artistevent',
            name='artist',
            field=models.ForeignKey(db_column='artistId', on_delete=django.db.models.deletion.CASCADE, to='artists.Artists'),
        ),
        migrations.AddField(
            model_name='artistevent',
            name='event',
            field=models.ForeignKey(db_column='eventId', on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
