# Generated by Django 2.0.4 on 2018-05-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_venue'),
        ('artists', '0002_auto_20180501_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='artists',
            name='events',
            field=models.ManyToManyField(through='artists.ArtistEvent', to='events.Event'),
        ),
        migrations.AddField(
            model_name='artistgenre',
            name='artist',
            field=models.ForeignKey(db_column='artistId', null=True, on_delete=django.db.models.deletion.CASCADE, to='artists.Artists'),
        ),
        migrations.AddField(
            model_name='artistgenre',
            name='genre',
            field=models.ForeignKey(db_column='genre', on_delete=django.db.models.deletion.CASCADE, to='artists.Genre'),
        ),
        migrations.AddField(
            model_name='artists',
            name='genres',
            field=models.ManyToManyField(through='artists.ArtistGenre', to='artists.Genre'),
        ),
    ]
