# Generated by Django 2.0.4 on 2018-05-04 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_venue'),
        ('artists', '0003_auto_20180501_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistevent',
            name='artist',
            field=models.ForeignKey(db_column='artistId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='artists.Artists'),
        ),
        migrations.AlterField(
            model_name='artistevent',
            name='event',
            field=models.ForeignKey(db_column='eventId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='events.Event'),
        ),
        migrations.RemoveField(
            model_name='artistevent',
            name='id',
        ),
        migrations.AlterUniqueTogether(
            name='artistevent',
            unique_together={('artist', 'event')},
        ),
    ]
