# Generated by Django 2.0.4 on 2018-05-04 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20180504_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistevent',
            name='event',
            field=models.ForeignKey(db_column='eventId', on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
