# Generated by Django 2.0.4 on 2018-05-04 03:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_auto_20180504_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistevent',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artistevent',
            name='artist',
            field=models.ForeignKey(db_column='artistId', on_delete=django.db.models.deletion.CASCADE, to='artists.Artists'),
        ),
    ]
