# Generated by Django 2.0.4 on 2018-05-04 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_auto_20180504_1225'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artistevent',
            table='artists_artistevents',
        ),
    ]
