# Generated by Django 2.0.4 on 2018-05-04 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0013_auto_20180504_1354'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artistevent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='artistevent',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artistevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='artists',
            name='events',
        ),
        migrations.DeleteModel(
            name='ArtistEvent',
        ),
    ]
