# Generated by Django 2.0.4 on 2018-05-04 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0017_auto_20180504_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='artistevent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='artistgenre',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='artistgenre',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='artistevent',
            name='updatedat',
            field=models.DateTimeField(blank=True, db_column='updatedAt', default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='artistgenre',
            name='updatedat',
            field=models.DateTimeField(blank=True, db_column='updatedAt', default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='genre',
            name='updatedat',
            field=models.DateTimeField(blank=True, db_column='updatedAt', default=datetime.datetime.now),
        ),
    ]
