# Generated by Django 2.0.4 on 2018-05-04 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0018_auto_20180504_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistevent',
            name='updatedat',
        ),
        migrations.RemoveField(
            model_name='artistgenre',
            name='updatedat',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='updatedat',
        ),
        migrations.AddField(
            model_name='artistevent',
            name='artistname',
            field=models.CharField(blank=True, db_column='artistName', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistevent',
            name='attractionid',
            field=models.CharField(blank=True, db_column='attractionId', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='artistgenre',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', null=True),
        ),
        migrations.AlterField(
            model_name='artistgenre',
            name='artist',
            field=models.ForeignKey(db_column='artistId', default=django.utils.timezone.now, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='artists.Artists'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artistgenre',
            name='genre',
            field=models.ForeignKey(db_column='genre', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='artists.Genre'),
        ),
    ]
