# Generated by Django 2.0.4 on 2018-05-08 11:42

from django.db import migrations
import lisztfeverapp.artists.models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0019_auto_20180504_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistevent',
            name='updated_at',
            field=lisztfeverapp.artists.models.UnixTimestampField(auto_created=True, db_column='updatedAt', null=True),
        ),
        migrations.AlterField(
            model_name='artistgenre',
            name='updated_at',
            field=lisztfeverapp.artists.models.UnixTimestampField(auto_created=True, db_column='updatedAt', null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='updated_at',
            field=lisztfeverapp.artists.models.UnixTimestampField(auto_created=True, db_column='updatedAt', null=True),
        ),
    ]
