# Generated by Django 2.0.4 on 2018-05-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venuename',
            field=models.CharField(blank=True, db_column='venueName', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('eventid', 'venue', 'venuename')},
        ),
    ]
