# Generated by Django 2.0.4 on 2018-05-01 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180501_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(db_column='venueId', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Venue'),
        ),
    ]
