# Generated by Django 2.0.4 on 2018-05-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_venue'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
    ]
