# Generated by Django 2.0.4 on 2018-05-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180511_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['eventstartlocaldate']},
        ),
    ]
